name: scan with KICS and upload SARIF

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '20 14 * * 1'

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-action@v1.2
        with:
          path: 'terraform'
          output_path: results-dir
          platform_type: terraform
          output_formats: 'sarif'
      - name: Show results
        if: ${{ always() }}
        run: |
          cat results-dir/results.sarif
      - name: Upload SARIF file
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results-dir/results.sarif
